name: contactlistwithhive
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  #database
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  
  #helpers
  uuid: ^3.0.5
  equatable: ^2.0.3
  dartz: ^0.10.1
  
  #state management
  flutter_bloc: ^8.0.0

  #services
  path_provider: ^2.0.8

  #service locator
  get_it: ^7.2.0

dev_dependencies:
  
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  mockito: ^5.0.16
  bloc_test: ^9.0.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true